name: Event content type
type: Starshot
recipes:
  - starshot_content_type_base
  - starshot_image_media_type
install:
  - address
  - geocoder_address
  - geocoder_geofield
  - layout_builder
  - leaflet
  - smart_date
config:
  import:
    filter:
      - filter.format.plain_text
    smart_date: '*'
  actions:
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.event:
          - basic
          - advanced
          - open_graph
    workflows.workflow.editorial:
      addNodeTypes:
        - event
